pipeline {
    agent any

    stages {
        stage('Checkout Dev Code') {
            steps {
                git branch: 'main', url: 'https://github.com/org/app-repo.git'
            }
        }

        stage('Checkout Test Scripts') {
            steps {
                git branch: 'main', url: 'https://github.com/Asik14/Nonpo_2.git'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}
